cadenota=''' 
pokemon('Bulbasaur').
pokemon('Ivysaur').
pokemon('Venusaur').
pokemon('Charmander').
pokemon('Charmeleon').
pokemon('Charizard').
pokemon('Squirtle').
pokemon('Wartortle').
pokemon('Blastoise').
pokemon('Caterpie').
pokemon('Metapod').
pokemon('Butterfree').
pokemon('Weedle').
pokemon('Kakuna').
pokemon('Beedrill').
pokemon('Pidgey').
pokemon('Pidgeotto').
pokemon('Pidgeot').
pokemon('Rattata').
pokemon('Raticate').
pokemon('Spearow').
pokemon('Fearow').
pokemon('Ekans').
pokemon('Arbok').
pokemon('Pikachu').
pokemon('Raichu').
pokemon('Sandshrew').
pokemon('Sandslash').
pokemon('Nidoran-F').
pokemon('Nidorina').
pokemon('Nidoqueen').
pokemon('Nidoran-M').
pokemon('Nidorino').
pokemon('Nidoking').
pokemon('Clefairy').
pokemon('Clefable').
pokemon('Vulpix').
pokemon('Ninetales').
pokemon('Jigglypuff').
pokemon('Wigglytuff').
pokemon('Zubat').
pokemon('Golbat').
pokemon('Oddish').
pokemon('Gloom').
pokemon('Vileplume').
pokemon('Paras').
pokemon('Parasect').
pokemon('Venonat').
pokemon('Venomoth').
pokemon('Diglett').
pokemon('Dugtrio').
pokemon('Meowth').
pokemon('Persian').
pokemon('Psyduck').
pokemon('Golduck').
pokemon('Mankey').
pokemon('Primeape').
pokemon('Growlithe').
pokemon('Arcanine').
pokemon('Poliwag').
pokemon('Poliwhirl').
pokemon('Poliwrath').
pokemon('Abra').
pokemon('Kadabra').
pokemon('Alakazam').
pokemon('Machop').
pokemon('Machoke').
pokemon('Machamp').
pokemon('Bellsprout').
pokemon('Weepinbell').
pokemon('Victreebel').
pokemon('Tentacool').
pokemon('Tentacruel').
pokemon('Geodude').
pokemon('Graveler').
pokemon('Golem').
pokemon('Ponyta').
pokemon('Rapidash').
pokemon('Slowpoke').
pokemon('Slowbro').
pokemon('Magnemite').
pokemon('Magneton').
pokemon('Farfetchd').
pokemon('Doduo').
pokemon('Dodrio').
pokemon('Seel').
pokemon('Dewgong').
pokemon('Grimer').
pokemon('Muk').
pokemon('Shellder').
pokemon('Cloyster').
pokemon('Gastly').
pokemon('Haunter').
pokemon('Gengar').
pokemon('Onix').
pokemon('Drowzee').
pokemon('Hypno').
pokemon('Krabby').
pokemon('Kingler').
pokemon('Voltorb').
pokemon('Electrode').
pokemon('Exeggcute').
pokemon('Exeggutor').
pokemon('Cubone').
pokemon('Marowak').
pokemon('Hitmonlee').
pokemon('Hitmonchan').
pokemon('Lickitung').
pokemon('Koffing').
pokemon('Weezing').
pokemon('Rhyhorn').
pokemon('Rhydon').
pokemon('Chansey').
pokemon('Tangela').
pokemon('Kangaskhan').
pokemon('Horsea').
pokemon('Seadra').
pokemon('Goldeen').
pokemon('Seaking').
pokemon('Staryu').
pokemon('Starmie').
pokemon('Mr.Mime').
pokemon('Scyther').
pokemon('Jynx').
pokemon('Electabuzz').
pokemon('Magmar').
pokemon('Pinsir').
pokemon('Tauros').
pokemon('Magikarp').
pokemon('Gyarados').
pokemon('Lapras').
pokemon('Ditto').
pokemon('Eevee').
pokemon('Vaporeon').
pokemon('Jolteon').
pokemon('Flareon').
pokemon('Porygon').
pokemon('Omanyte').
pokemon('Omastar').
pokemon('Kabuto').
pokemon('Kabutops').
pokemon('Aerodactyl').
pokemon('Snorlax').
pokemon('Articuno').
pokemon('Zapdos').
pokemon('Moltres').
pokemon('Dratini').
pokemon('Dragonair').
pokemon('Dragonite').
pokemon('Mewtwo').
pokemon('Mew').
pokemon('Chikorita').
pokemon('Bayleef').
pokemon('Meganium').
pokemon('Cyndaquil').
pokemon('Quilava').
pokemon('Typhlosion').
pokemon('Totodile').
pokemon('Croconaw').
pokemon('Feraligatr').
pokemon('Sentret').
pokemon('Furret').
pokemon('Hoothoot').
pokemon('Noctowl').
pokemon('Ledyba').
pokemon('Ledian').
pokemon('Spinarak').
pokemon('Ariados').
pokemon('Crobat').
pokemon('Chinchou').
pokemon('Lanturn').
pokemon('Pichu').
pokemon('Cleffa').
pokemon('Igglybuff').
pokemon('Togepi').
pokemon('Togetic').
pokemon('Natu').
pokemon('Xatu').
pokemon('Mareep').
pokemon('Flaaffy').
pokemon('Ampharos').
pokemon('Bellossom').
pokemon('Marill').
pokemon('Azumarill').
pokemon('Sudowoodo').
pokemon('Politoed').
pokemon('Hoppip').
pokemon('Skiploom').
pokemon('Jumpluff').
pokemon('Aipom').
pokemon('Sunkern').
pokemon('Sunflora').
pokemon('Yanma').
pokemon('Wooper').
pokemon('Quagsire').
pokemon('Espeon').
pokemon('Umbreon').
pokemon('Murkrow').
pokemon('Slowking').
pokemon('Misdreavus').
pokemon('Unown').
pokemon('Wobbuffet').
pokemon('Girafarig').
pokemon('Pineco').
pokemon('Forretress').
pokemon('Dunsparce').
pokemon('Gligar').
pokemon('Steelix').
pokemon('Snubbull').
pokemon('Granbull').
pokemon('Qwilfish').
pokemon('Scizor').
pokemon('Shuckle').
pokemon('Heracross').
pokemon('Sneasel').
pokemon('Teddiursa').
pokemon('Ursaring').
pokemon('Slugma').
pokemon('Magcargo').
pokemon('Swinub').
pokemon('Piloswine').
pokemon('Corsola').
pokemon('Remoraid').
pokemon('Octillery').
pokemon('Delibird').
pokemon('Mantine').
pokemon('Skarmory').
pokemon('Houndour').
pokemon('Houndoom').
pokemon('Kingdra').
pokemon('Phanpy').
pokemon('Donphan').
pokemon('Porygon2').
pokemon('Stantler').
pokemon('Smeargle').
pokemon('Tyrogue').
pokemon('Hitmontop').
pokemon('Smoochum').
pokemon('Elekid').
pokemon('Magby').
pokemon('Miltank').
pokemon('Blissey').
pokemon('Raikou').
pokemon('Entei').
pokemon('Suicune').
pokemon('Larvitar').
pokemon('Pupitar').
pokemon('Tyranitar').
pokemon('Lugia').
pokemon('Ho-Oh').
pokemon('Celebi').
pokemon('Treecko').
pokemon('Grovyle').
pokemon('Sceptile').
pokemon('Torchic').
pokemon('Combusken').
pokemon('Blaziken').
pokemon('Mudkip').
pokemon('Marshtomp').
pokemon('Swampert').
pokemon('Poochyena').
pokemon('Mightyena').
pokemon('Zigzagoon').
pokemon('Linoone').
pokemon('Wurmple').
pokemon('Silcoon').
pokemon('Beautifly').
pokemon('Cascoon').
pokemon('Dustox').
pokemon('Lotad').
pokemon('Lombre').
pokemon('Ludicolo').
pokemon('Seedot').
pokemon('Nuzleaf').
pokemon('Shiftry').
pokemon('Taillow').
pokemon('Swellow').
pokemon('Wingull').
pokemon('Pelipper').
pokemon('Ralts').
pokemon('Kirlia').
pokemon('Gardevoir').
pokemon('Surskit').
pokemon('Masquerain').
pokemon('Shroomish').
pokemon('Breloom').
pokemon('Slakoth').
pokemon('Vigoroth').
pokemon('Slaking').
pokemon('Nincada').
pokemon('Ninjask').
pokemon('Shedinja').
pokemon('Whismur').
pokemon('Loudred').
pokemon('Exploud').
pokemon('Makuhita').
pokemon('Hariyama').
pokemon('Azurill').
pokemon('Nosepass').
pokemon('Skitty').
pokemon('Delcatty').
pokemon('Sableye').
pokemon('Mawile').
pokemon('Aron').
pokemon('Lairon').
pokemon('Aggron').
pokemon('Meditite').
pokemon('Medicham').
pokemon('Electrike').
pokemon('Manectric').
pokemon('Plusle').
pokemon('Minun').
pokemon('Volbeat').
pokemon('Illumise').
pokemon('Roselia').
pokemon('Gulpin').
pokemon('Swalot').
pokemon('Carvanha').
pokemon('Sharpedo').
pokemon('Wailmer').
pokemon('Wailord').
pokemon('Numel').
pokemon('Camerupt').
pokemon('Torkoal').
pokemon('Spoink').
pokemon('Grumpig').
pokemon('Spinda').
pokemon('Trapinch').
pokemon('Vibrava').
pokemon('Flygon').
pokemon('Cacnea').
pokemon('Cacturne').
pokemon('Swablu').
pokemon('Altaria').
pokemon('Zangoose').
pokemon('Seviper').
pokemon('Lunatone').
pokemon('Solrock').
pokemon('Barboach').
pokemon('Whiscash').
pokemon('Corphish').
pokemon('Crawdaunt').
pokemon('Baltoy').
pokemon('Claydol').
pokemon('Lileep').
pokemon('Cradily').
pokemon('Anorith').
pokemon('Armaldo').
pokemon('Feebas').
pokemon('Milotic').
pokemon('Castform').
pokemon('Kecleon').
pokemon('Shuppet').
pokemon('Banette').
pokemon('Duskull').
pokemon('Dusclops').
pokemon('Tropius').
pokemon('Chimecho').
pokemon('Absol').
pokemon('Wynaut').
pokemon('Snorunt').
pokemon('Glalie').
pokemon('Spheal').
pokemon('Sealeo').
pokemon('Walrein').
pokemon('Clamperl').
pokemon('Huntail').
pokemon('Gorebyss').
pokemon('Relicanth').
pokemon('Luvdisc').
pokemon('Bagon').
pokemon('Shelgon').
pokemon('Salamence').
pokemon('Beldum').
pokemon('Metang').
pokemon('Metagross').
pokemon('Regirock').
pokemon('Regice').
pokemon('Registeel').
pokemon('Latias').
pokemon('Latios').
pokemon('Kyogre').
pokemon('Groudon').
pokemon('Rayquaza').
pokemon('Jirachi').
pokemon('Deoxys').
pokemon('Turtwig').
pokemon('Grotle').
pokemon('Torterra').
pokemon('Chimchar').
pokemon('Monferno').
pokemon('Infernape').
pokemon('Piplup').
pokemon('Prinplup').
pokemon('Empoleon').
pokemon('Starly').
pokemon('Staravia').
pokemon('Staraptor').
pokemon('Bidoof').
pokemon('Bibarel').
pokemon('Kricketot').
pokemon('Kricketune').
pokemon('Shinx').
pokemon('Luxio').
pokemon('Luxray').
pokemon('Budew').
pokemon('Roserade').
pokemon('Cranidos').
pokemon('Rampardos').
pokemon('Shieldon').
pokemon('Bastiodon').
pokemon('Burmy').
pokemon('Wormadam').
pokemon('Mothim').
pokemon('Combee').
pokemon('Vespiquen').
pokemon('Pachirisu').
pokemon('Buizel').
pokemon('Floatzel').
pokemon('Cherubi').
pokemon('Cherrim').
pokemon('Shellos').
pokemon('Gastrodon').
pokemon('Ambipom').
pokemon('Drifloon').
pokemon('Drifblim').
pokemon('Buneary').
pokemon('Lopunny').
pokemon('Mismagius').
pokemon('Honchkrow').
pokemon('Glameow').
pokemon('Purugly').
pokemon('Chingling').
pokemon('Stunky').
pokemon('Skuntank').
pokemon('Bronzor').
pokemon('Bronzong').
pokemon('Bonsly').
pokemon('Mime-Jr.').
pokemon('Happiny').
pokemon('Chatot').
pokemon('Spiritomb').
pokemon('Gible').
pokemon('Gabite').
pokemon('Garchomp').
pokemon('Munchlax').
pokemon('Riolu').
pokemon('Lucario').
pokemon('Hippopotas').
pokemon('Hippowdon').
pokemon('Skorupi').
pokemon('Drapion').
pokemon('Croagunk').
pokemon('Toxicroak').
pokemon('Carnivine').
pokemon('Finneon').
pokemon('Lumineon').
pokemon('Mantyke').
pokemon('Snover').
pokemon('Abomasnow').
pokemon('Weavile').
pokemon('Magnezone').
pokemon('Lickilicky').
pokemon('Rhyperior').
pokemon('Tangrowth').
pokemon('Electivire').
pokemon('Magmortar').
pokemon('Togekiss').
pokemon('Yanmega').
pokemon('Leafeon').
pokemon('Glaceon').
pokemon('Gliscor').
pokemon('Mamoswine').
pokemon('Porygon-Z').
pokemon('Gallade').
pokemon('Probopass').
pokemon('Dusknoir').
pokemon('Froslass').
pokemon('Rotom').
pokemon('Uxie').
pokemon('Mesprit').
pokemon('Azelf').
pokemon('Dialga').
pokemon('Palkia').
pokemon('Heatran').
pokemon('Regigigas').
pokemon('Giratina').
pokemon('Cresselia').
pokemon('Phione').
pokemon('Manaphy').
pokemon('Darkrai').
pokemon('Shaymin').
pokemon('Arceus').
pokemon('Victini').
pokemon('Snivy').
pokemon('Servine').
pokemon('Serperior').
pokemon('Tepig').
pokemon('Pignite').
pokemon('Emboar').
pokemon('Oshawott').
pokemon('Dewott').
pokemon('Samurott').
pokemon('Patrat').
pokemon('Watchog').
pokemon('Lillipup').
pokemon('Herdier').
pokemon('Stoutland').
pokemon('Purrloin').
pokemon('Liepard').
pokemon('Pansage').
pokemon('Simisage').
pokemon('Pansear').
pokemon('Simisear').
pokemon('Panpour').
pokemon('Simipour').
pokemon('Munna').
pokemon('Musharna').
pokemon('Pidove').
pokemon('Tranquill').
pokemon('Unfezant').
pokemon('Blitzle').
pokemon('Zebstrika').
pokemon('Roggenrola').
pokemon('Boldore').
pokemon('Gigalith').
pokemon('Woobat').
pokemon('Swoobat').
pokemon('Drilbur').
pokemon('Excadrill').
pokemon('Audino').
pokemon('Timburr').
pokemon('Gurdurr').
pokemon('Conkeldurr').
pokemon('Tympole').
pokemon('Palpitoad').
pokemon('Seismitoad').
pokemon('Throh').
pokemon('Sawk').
pokemon('Sewaddle').
pokemon('Swadloon').
pokemon('Leavanny').
pokemon('Venipede').
pokemon('Whirlipede').
pokemon('Scolipede').
pokemon('Cottonee').
pokemon('Whimsicott').
pokemon('Petilil').
pokemon('Lilligant').
pokemon('Basculin').
pokemon('Sandile').
pokemon('Krokorok').
pokemon('Krookodile').
pokemon('Darumaka').
pokemon('Darmanitan').
pokemon('Maractus').
pokemon('Dwebble').
pokemon('Crustle').
pokemon('Scraggy').
pokemon('Scrafty').
pokemon('Sigilyph').
pokemon('Yamask').
pokemon('Cofagrigus').
pokemon('Tirtouga').
pokemon('Carracosta').
pokemon('Archen').
pokemon('Archeops').
pokemon('Trubbish').
pokemon('Garbodor').
pokemon('Zorua').
pokemon('Zoroark').
pokemon('Minccino').
pokemon('Cinccino').
pokemon('Gothita').
pokemon('Gothorita').
pokemon('Gothitelle').
pokemon('Solosis').
pokemon('Duosion').
pokemon('Reuniclus').
pokemon('Ducklett').
pokemon('Swanna').
pokemon('Vanillite').
pokemon('Vanillish').
pokemon('Vanilluxe').
pokemon('Deerling').
pokemon('Sawsbuck').
pokemon('Emolga').
pokemon('Karrablast').
pokemon('Escavalier').
pokemon('Foongus').
pokemon('Amoonguss').
pokemon('Frillish').
pokemon('Jellicent').
pokemon('Alomomola').
pokemon('Joltik').
pokemon('Galvantula').
pokemon('Ferroseed').
pokemon('Ferrothorn').
pokemon('Klink').
pokemon('Klang').
pokemon('Klinklang').
pokemon('Tynamo').
pokemon('Eelektrik').
pokemon('Eelektross').
pokemon('Elgyem').
pokemon('Beheeyem').
pokemon('Litwick').
pokemon('Lampent').
pokemon('Chandelure').
pokemon('Axew').
pokemon('Fraxure').
pokemon('Haxorus').
pokemon('Cubchoo').
pokemon('Beartic').
pokemon('Cryogonal').
pokemon('Shelmet').
pokemon('Accelgor').
pokemon('Stunfisk').
pokemon('Mienfoo').
pokemon('Mienshao').
pokemon('Druddigon').
pokemon('Golett').
pokemon('Golurk').
pokemon('Pawniard').
pokemon('Bisharp').
pokemon('Bouffalant').
pokemon('Rufflet').
pokemon('Braviary').
pokemon('Vullaby').
pokemon('Mandibuzz').
pokemon('Heatmor').
pokemon('Durant').
pokemon('Deino').
pokemon('Zweilous').
pokemon('Hydreigon').
pokemon('Larvesta').
pokemon('Volcarona').
pokemon('Cobalion').
pokemon('Terrakion').
pokemon('Virizion').
pokemon('Tornadus').
pokemon('Thundurus').
pokemon('Reshiram').
pokemon('Zekrom').
pokemon('Landorus').
pokemon('Kyurem').
pokemon('Keldeo').
pokemon('Meloetta').
pokemon('Genesect').
pokemon('Chespin').
pokemon('Quilladin').
pokemon('Chesnaught').
pokemon('Fennekin').
pokemon('Braixen').
pokemon('Delphox').
pokemon('Froakie').
pokemon('Frogadier').
pokemon('Greninja').
pokemon('Bunnelby').
pokemon('Diggersby').
pokemon('Fletchling').
pokemon('Fletchinder').
pokemon('Talonflame').
pokemon('Scatterbug').
pokemon('Spewpa').
pokemon('Vivillon').
pokemon('Litleo').
pokemon('Pyroar').
pokemon('Flabébé').
pokemon('Floette').
pokemon('Florges').
pokemon('Skiddo').
pokemon('Gogoat').
pokemon('Pancham').
pokemon('Pangoro').
pokemon('Furfrou').
pokemon('Espurr').
pokemon('Meowstic').
pokemon('Honedge').
pokemon('Doublade').
pokemon('Aegislash').
pokemon('Spritzee').
pokemon('Aromatisse').
pokemon('Swirlix').
pokemon('Slurpuff').
pokemon('Inkay').
pokemon('Malamar').
pokemon('Binacle').
pokemon('Barbaracle').
pokemon('Skrelp').
pokemon('Dragalge').
pokemon('Clauncher').
pokemon('Clawitzer').
pokemon('Helioptile').
pokemon('Heliolisk').
pokemon('Tyrunt').
pokemon('Tyrantrum').
pokemon('Amaura').
pokemon('Aurorus').
pokemon('Sylveon').
pokemon('Hawlucha').
pokemon('Dedenne').
pokemon('Carbink').
pokemon('Goomy').
pokemon('Sliggoo').
pokemon('Goodra').
pokemon('Klefki').
pokemon('Phantump').
pokemon('Trevenant').
pokemon('Pumpkaboo').
pokemon('Gourgeist').
pokemon('Bergmite').
pokemon('Avalugg').
pokemon('Noibat').
pokemon('Noivern').
pokemon('Xerneas').
pokemon('Yveltal').
pokemon('Zygarde').
pokemon('Diancie').
pokemon('Hoopa').
pokemon('Volcanion').
pokemon('Rowlet').
pokemon('Dartrix').
pokemon('Decidueye').
pokemon('Litten').
pokemon('Torracat').
pokemon('Incineroar').
pokemon('Popplio').
pokemon('Brionne').
pokemon('Primarina').
pokemon('Pikipek').
pokemon('Trumbeak').
pokemon('Toucannon').
pokemon('Yungoos').
pokemon('Gumshoos').
pokemon('Grubbin').
pokemon('Charjabug').
pokemon('Vikavolt').
pokemon('Crabrawler').
pokemon('Crabominable').
pokemon('Oricorio').
pokemon('Cutiefly').
pokemon('Ribombee').
pokemon('Rockruff').
pokemon('Lycanroc').
pokemon('Wishiwashi').
pokemon('Mareanie').
pokemon('Toxapex').
pokemon('Mudbray').
pokemon('Mudsdale').
pokemon('Dewpider').
pokemon('Araquanid').
pokemon('Fomantis').
pokemon('Lurantis').
pokemon('Morelull').
pokemon('Shiinotic').
pokemon('Salandit').
pokemon('Salazzle').
pokemon('Stufful').
pokemon('Bewear').
pokemon('Bounsweet').
pokemon('Steenee').
pokemon('Tsareena').
pokemon('Comfey').
pokemon('Oranguru').
pokemon('Passimian').
pokemon('Wimpod').
pokemon('Golisopod').
pokemon('Sandygast').
pokemon('Palossand').
pokemon('Pyukumuku').
pokemon('Type:Null').
pokemon('Silvally').
pokemon('Minior').
pokemon('Komala').
pokemon('Turtonator').
pokemon('Togedemaru').
pokemon('Mimikyu').
pokemon('Bruxish').
pokemon('Drampa').
pokemon('Dhelmise').
pokemon('Jangmo-o').
pokemon('Hakamo-o').
pokemon('Kommo-o').
pokemon('Tapu-Koko').
pokemon('Tapu-Lele').
pokemon('Tapu-Bulu').
pokemon('Tapu-Fini').
pokemon('Cosmog').
pokemon('Cosmoem').
pokemon('Solgaleo').
pokemon('Lunala').
pokemon('Nihilego').
pokemon('Buzzwole').
pokemon('Pheromosa').
pokemon('Xurkitree').
pokemon('Celesteela').
pokemon('Kartana').
pokemon('Guzzlord').
pokemon('Necrozma').
pokemon('Magearna').
pokemon('Marshadow').
pokemon('Poipole').
pokemon('Naganadel').
pokemon('Stakataka').
pokemon('Blacephalon').
pokemon('Zeraora').
pokemon('Meltan').
pokemon('Melmetal').
pokemon('Missingno').
'''
colores_de_pokes='''
color('Amarillo','Abra').
color('Amarillo','Aegislash').
color('Amarillo','Alakazam').
color('Amarillo','Ampharos').
color('Amarillo','Bayleef').
color('Amarillo','Beedrill').
color('Amarillo','Bellsprout').
color('Amarillo','Braixen').
color('Amarillo','Bruxish').
color('Amarillo','Chingling').
color('Amarillo','Cosmoem').
color('Amarillo','Cutiefly').
color('Amarillo','Drowzee').
color('Amarillo','Dunsparce').
color('Amarillo','Electabuzz').
color('Amarillo','Electivire').
color('Amarillo','Elekid').
color('Amarillo','Fennekin').
color('Amarillo','Flabébé').
color('Amarillo','Galvantula').
color('Amarillo','Girafarig').
color('Amarillo','Haxorus').
color('Amarillo','Heliolisk').
color('Amarillo','Helioptile').
color('Amarillo','Hypno').
color('Amarillo','Jirachi').
color('Amarillo','Jolteon').
color('Amarillo','Joltik').
color('Amarillo','Kadabra').
color('Amarillo','Kakuna').
color('Amarillo','Lunatone').
color('Amarillo','Makuhita').
color('Amarillo','Mega-Alakazam').
color('Amarillo','Mega-Ampharos').
color('Amarillo','Mega-Beedrill').
color('Amarillo','Mienfoo').
color('Amarillo','Ninetales').
color('Amarillo','Numel').
color('Amarillo','Pichu').
color('Amarillo','Pikachu').
color('Amarillo','Psyduck').
color('Amarillo','Raichu').
color('Amarillo','Raikou').
color('Amarillo','Ribombee').
color('Amarillo','Rotom-Ventilador').
color('Amarillo','Sableye').
color('Amarillo','Sandshrew').
color('Amarillo','Sandslash').
color('Amarillo','Shuckle').
color('Amarillo','Snorunt').%%%%%%%%%%%%%%%%%%%
color('Amarillo','Sunflora').
color('Amarillo','Sunkern').
color('Amarillo','Togepi').
color('Amarillo','Turtonator').
color('Amarillo','Victreebel').
color('Amarillo','Weepinbell').
color('Amarillo','Zapdos').
color('Amarillo','Zeraora').
color('Azul','Altaria').
color('Azul','Amaura').
color('Azul','Armaldo').
color('Azul','Articuno').
color('Azul','Aurorus').
color('Azul','Avalugg').
color('Azul','Azelf').
color('Azul','Azumarill').
color('Azul','Bagon').
color('Azul','Bergmite').
color('Azul','Blastoise').
color('Azul','Boldore').
color('Azul','Braviary').
color('Azul','Brionne').
color('Azul','Bronzong').
color('Azul','Bronzor').
color('Azul','Carnivine').
color('Azul','Carracosta').
color('Azul','Carvanha').
color('Azul','Chinchou').
color('Azul','Clamperl').
color('Azul','Clauncher').
color('Azul','Clawitzer').
color('Azul','Cobalion').
color('Azul','Cresselia').
color('Azul','Croconaw').
color('Azul','Cryogonal').
color('Azul','Cubchoo').
color('Azul','Deino').
color('Azul','Dewott').
color('Azul','Dhelmise').
color('Azul','Dialga').
color('Azul','Donphan').
color('Azul','Dragonair').
color('Azul','Dratini').
color('Azul','Druddigon').
color('Azul','Ducklett').
color('Azul','Eelektrik').
color('Azul','Eelektross').
color('Azul','Elgyem').
color('Azul','Empoleon').
color('Azul','Feraligatr').
color('Azul','Frillish').
color('Azul','Froakie').
color('Azul','Frogadier').
color('Azul','Gabite').
color('Azul','Garchomp').
color('Azul','Gastrodon').
color('Azul','Gible').
color('Azul','Gigalith').
color('Azul','Glaceon').
color('Azul','Gloom').
color('Azul','Golbat').
color('Azul','Golduck').
color('Azul','Golett').
color('Azul','Golurk').
color('Azul','Greninja').
color('Azul','Gyarados').
color('Azul','Hariyama').
color('Azul','Heracross').
color('Azul','Hippopotas').
color('Azul','Hitmontop').
color('Azul','Honchkrow').
color('Azul','Horsea').
color('Azul','Huntail').
color('Azul','Hydreigon').
color('Azul','Inkay').
color('Azul','Ivysaur').
color('Azul','Jellicent').
color('Azul','Jumpluff').
color('Azul','Karrablast').
color('Azul','Kingdra').
color('Azul','Komala').
color('Azul','Kyogre').
color('Azul','Lanturn').
color('Azul','Lapras').
color('Azul','Latios').
color('Azul','Lotad').
color('Azul','Lucario').
color('Azul','Lumineon').
color('Azul','Luxio').
color('Azul','Luxray').
color('Azul','Machamp').
color('Azul','Machoke').
color('Azul','Machop').
color('Azul','Manaphy').
color('Azul','Manectric').
color('Azul','Mantyke').
color('Azul','Mareanie').
color('Azul','Mareep').
color('Azul','Marill').
color('Azul','Marshtomp').
color('Azul','Meditite').
color('Azul','Mega-Blastoise').
color('Azul','Mega-Garchomp').
color('Azul','Mega-Gyarados').
color('Azul','Mega-Heracross').
color('Azul','Mega-Latios').
color('Azul','Mega-Lucario').
color('Azul','Mega-Manectric').
color('Azul','Mega-Metagross').
color('Azul','Mega-Salamence').
color('Azul','Mega-Sharpedo').
color('Azul','Mega-Swampert').
color('Azul','Mesprit').
color('Azul','Mudkip').
color('Azul','Munchlax').
color('Azul','Nidoqueen').
color('Azul','Nidoran♀').
color('Azul','Nidorina').
color('Azul','Ninetales-de-Alola').
color('Azul','Oddish').
color('Azul','Omanyte').
color('Azul','Omastar').
color('Azul','Oshawott').
color('Azul','Palpitoad').
color('Azul','Panpour').
color('Azul','Phanpy').
color('Azul','Phione').
color('Azul','Piplup').
color('Azul','Poliwag').
color('Azul','Poliwhirl').
color('Azul','Poliwrath').
color('Azul','Popplio').
color('Azul','Primarina').
color('Azul','Prinplup').
color('Azul','Probopass').
color('Azul','Quagsire').
color('Azul','Regice').
color('Azul','Remoraid').
color('Azul','Riolu').
color('Azul','Roggenrola').
color('Azul','Rotom-Lavado').
color('Azul','Salamence').
color('Azul','Samurott').
color('Azul','Sandshrew-de-Alola').
color('Azul','Sandslash-de-Alola').
color('Azul','Sawk').
color('Azul','Seadra').
color('Azul','Sealeo').
color('Azul','Seismitoad').
color('Azul','Sharpedo').
color('Azul','Shinx').
color('Azul','Simisear').
color('Azul','Sneasel').
color('Azul','Snorlax').
color('Azul','Spheal').
color('Azul','Squirtle').
color('Azul','Suicune').
color('Azul','Surskit').
color('Azul','Swablu').
color('Azul','Swampert').
color('Azul','Swellow').
color('Azul','Swoobat').
color('Azul','Taillow').
color('Azul','Tangela').
color('Azul','Tangrowth').
color('Azul','Tentacool').
color('Azul','Tentacruel').
color('Azul','Thundurus').
color('Azul','Thundurus-Therian').
color('Azul','Tirtouga').
color('Azul','Totodile').
color('Azul','Toxapex').
color('Azul','Toxicroak').
color('Azul','Tympole').
color('Azul','Uxie').
color('Azul','Vanillish').
color('Azul','Vanilluxe').
color('Azul','Vaporeon').
color('Azul','Venusaur').
color('Azul','Vikavolt').
color('Azul','Vileplume').
color('Azul','Vulpix-de-Alola').
color('Azul','Wailmer').
color('Azul','Wailord').
color('Azul','Walrein').
color('Azul','Wartortle').
color('Azul','Whiscash').
color('Azul','Wobbuffet').
color('Azul','Woobat').
color('Azul','Wooper').
color('Azul','Wynaut').
color('Azul','Zebstrika').
color('Azul','Zubat').
color('Azul','Zweilous').
color('Beige','Baltoy').
color('Beige','Chesnaught').
color('Beige','Cyndaquil').
color('Beige','Foongus').
color('Beige','Keldeo').
color('Beige','Keldeo-Resolete').
color('Beige','Leafeon').
color('Beige','Mankey').
color('Beige','Mega-Mawile').
color('Beige','Mega-Pidgeot').
color('Beige','Meowth').
color('Beige','Milotic').
color('Beige','Mimikyu').
color('Beige','Minun').
color('Beige','Persian').
color('Beige','Plusle').
color('Beige','Ponyta').
color('Beige','Primeape').
color('Beige','Quilava').
color('Beige','Rapidash').
color('Beige','Shroomish').
color('Beige','Slakoth').
color('Beige','Smeargle').
color('Beige','Spinda').
color('Beige','Typhlosion').
color('Beige','Victini').
color('Blanco','Abomasnow').
color('Blanco','Absol').
color('Blanco','Aerodactyl').
color('Blanco','Arceus').
color('Blanco','Beartic').
color('Blanco','Blacephalon').
color('Blanco','Cascoon').
color('Blanco','Chimecho').
color('Blanco','Cottonee').
color('Blanco','Crabominable').
color('Blanco','Dewgong').
color('Blanco','Diancie').
color('Blanco','Drampa').
color('Blanco','Electrode').
color('Blanco','Emolga').
color('Blanco','Exeggcute').
color('Blanco','Floette').
color('Blanco','Forretress').
color('Blanco','Froslass').
color('Blanco','Furfrou').
color('Blanco','Gallade').
color('Blanco','Gardevoir').
color('Blanco','Glalie').
color('Blanco','Goldeen').
color('Blanco','Grubbin').
color('Blanco','Kartana').
color('Blanco','Kirlia').
color('Blanco','Klefki').
color('Blanco','Larvesta').
color('Blanco','Litwick').
color('Blanco','Lugia').
color('Blanco','Magearna').
color('Blanco','Mantine').
color('Blanco','Masquerain').
color('Blanco','Mawile').
color('Blanco','Mega-Abomasnow').
color('Blanco','Mega-Absol').
color('Blanco','Mega-Altaria').
color('Blanco','Mega-Audino').
color('Blanco','Mega-Gallade').
color('Blanco','Mega-Gardevoir').
color('Blanco','Mega-Medicham').
color('Blanco','Mega-Mewtwo-X').
color('Blanco','Mega-Mewtwo-Y').
color('Blanco','Meloetta').
color('Blanco','Meloetta-Pirueta').
color('Blanco','Meowstic').
color('Blanco','Mewtwo').
color('Blanco','Mienshao').
color('Blanco','Minccino').
color('Blanco','Morelull').
color('Blanco','Nihilego').
color('Blanco','Nincada').
color('Blanco','Oranguru').
color('Blanco','Pachirisu').
color('Blanco','Palkia').
color('Blanco','Passimian').
color('Blanco','Pelipper').
color('Blanco','Pheromosa').
color('Blanco','Ralts').
color('Blanco','Regigigas').
color('Blanco','Reshiram').
color('Blanco','Rufflet').
color('Blanco','Seaking').
color('Blanco','Seel').
color('Blanco','Shiinotic').
color('Blanco','Silcoon').
color('Blanco','Silvally').
color('Blanco','Skarmory').
color('Blanco','Snover').
color('Blanco','Solgaleo').
color('Blanco','Spewpa').
color('Blanco','Steenee').
color('Blanco','Swanna').
color('Blanco','Swirlix').
color('Blanco','Sylveon').
color('Blanco','Togedemaru').
color('Blanco','Togekiss').
color('Blanco','Togetic').
color('Blanco','Tsareena').
color('Blanco','Tynamo').
color('Blanco','Vanillite').
color('Blanco','Venomoth').
color('Blanco','Vigoroth').
color('Blanco','Wingull').
color('Blanco','Wishiwashi').
color('Blanco','Zangoose').
color('Cafe','Barbaracle').
color('Cafe','Basculin').
color('Cafe','Beheeyem').
color('Cafe','Bibarel').
color('Cafe','Bidoof').
color('Cafe','Bonsly').
color('Cafe','Bouffalant').
color('Cafe','Buneary').
color('Cafe','Chespin').
color('Cafe','Chimchar').
color('Cafe','Conkeldurr').
color('Cafe','Cubone').
color('Cafe','Dartrix').
color('Cafe','Decidueye').
color('Cafe','Diglett').
color('Cafe','Diglett-de-Alola').
color('Cafe','Dodrio').
color('Cafe','Doduo').
color('Cafe','Doublade').
color('Cafe','Dragalge').
color('Cafe','Drilbur').
color('Cafe','Dugtrio').
color('Cafe','Dugtrio-de-Alola').
color('Cafe','Eevee').
color('Cafe','Entei').
color('Cafe','Excadrill').
color('Cafe','Exeggutor').
color('Cafe','Exeggutor-de-Alola').
color('Cafe','Farfetch’d').
color('Cafe','Fearow').
color('Cafe','Feebas').
color('Cafe','Furret').
color('Cafe','Garbodor').
color('Cafe','Geodude').
color('Cafe','Gogoat').
color('Cafe','Golem').
color('Cafe','Golem-de-Alola').
color('Cafe','Gourgeist').
color('Cafe','Graveler').
color('Cafe','Graveler-de-Alola').
color('Cafe','Gumshoos').
color('Cafe','Gurdurr').
color('Cafe','Heatran').
color('Cafe','Herdier').
color('Cafe','Hippowdon').
color('Cafe','Hitmonchan').
color('Cafe','Hitmonlee').
color('Cafe','Honedge').
color('Cafe','Hoothoot').
color('Cafe','Infernape').
color('Cafe','Kabuto').
color('Cafe','Kabutops').
color('Cafe','Kangaskhan').
color('Cafe','Lillipup').
color('Cafe','Linoone').
color('Cafe','Litleo').
color('Cafe','Lopunny').
color('Cafe','Lycanroc').
color('Cafe','Mamoswine').
color('Cafe','Mandibuzz').
color('Cafe','Marowak').
color('Cafe','Mega-Kangskhan').
color('Cafe','Mega-Lopunny').
color('Cafe','Mega-Pinsir').
color('Cafe','Minior').
color('Cafe','Monferno').
color('Cafe','Mudbray').
color('Cafe','Mudsdale').
color('Cafe','Noctowl').
color('Cafe','Nuzleaf').
color('Cafe','Palossand').
color('Cafe','Patrat').
color('Cafe','Phantump').
color('Cafe','Pidgeot').
color('Cafe','Pidgeotto').
color('Cafe','Pidgey').
color('Cafe','Piloswine').
color('Cafe','Pinsir').
color('Cafe','Pumpkaboo').
color('Cafe','Pyroar').
color('Cafe','Quilladin').
color('Cafe','Raichu-de-Alola').
color('Cafe','Raticate').
color('Cafe','Raticate-de-Alola').
color('Cafe','Rattata-de-Alola').
color('Cafe','Regirock').
color('Cafe','Relicanth').
color('Cafe','Rockruff').
color('Cafe','Rowlet').
color('Cafe','Sandile').
color('Cafe','Sandygast').
color('Cafe','Sawsbuck').
color('Cafe','Seedot').
color('Cafe','Sentret').
color('Cafe','Shedinja').
color('Cafe','Shiftry').
color('Cafe','Skiddo').
color('Cafe','Skorupi').
color('Cafe','Slaking').
color('Cafe','Spearow').
color('Cafe','Stantler').
color('Cafe','Staryu').
color('Cafe','Stoutland').
color('Cafe','Sudowoodo').
color('Cafe','Swinub').
color('Cafe','Tauros').
color('Cafe','Timburr').
color('Cafe','Trevenant').
color('Cafe','Tyrunt').
color('Cafe','Ursaring').
color('Cafe','Vullaby').
color('Cafe','Vulpix').
color('Cafe','Watchog').
color('Cafe','Weedle').
color('Cafe','Whimsicott').
color('Cafe','Yungoos').
color('Cafe','Zigzagoon').
color('Gris','Accelgor').
color('Gris','Aggron').
color('Gris','Amoonguss').
color('Gris','Aron').
color('Gris','Azurill').
color('Gris','Banette').
color('Gris','Barboach').
color('Gris','Beldum').
color('Gris','Bunnelby').
color('Gris','Carbink').
color('Gris','Castform').
color('Gris','Cinccino').
color('Gris','Cranidos').
color('Gris','Diggersby').
color('Gris','Durant').
color('Gris','Dusclops').
color('Gris','Dusknoir').
color('Gris','Duskull').
color('Gris','Escavalier').
color('Gris','Espurr').
color('Gris','Ferroseed').
color('Gris','Ferrothorn').
color('Gris','Geodude-de-Alola').
color('Gris','Giratina').
color('Gris','Glameow').
color('Gris','Golisopod').
color('Gris','Hakamo-o').
color('Gris','Hoopa').
color('Gris','Jangmo-o').
color('Gris','Klang').
color('Gris','Klink').
color('Gris','Klinklang').
color('Gris','Kommo-o').
color('Gris','Kyurem').
color('Gris','Lairon').
color('Gris','Magnemite').
color('Gris','Magneton').
color('Gris','Magnezone').
color('Gris','Mega-Aggron').
color('Gris','Mega-Diancie').
color('Gris','Mega-Glalie').
color('Gris','Mega-Steelix').
color('Gris','Melmetal').%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
color('Gris','Meltan').
color('Gris','Metagross').
color('Gris','Metang').
color('Gris','Musharna').
color('Gris','Onix').
color('Gris','Pancham').
color('Gris','Pangoro').
color('Gris','Pawniard').
color('Gris','Pidove').
color('Gris','Poochyena').
color('Gris','Pupitar').
color('Gris','Purugly').
color('Gris','Registeel').
color('Gris','Rhydon').
color('Gris','Rhyhorn').
color('Gris','Rhyperior').
color('Gris','Scatterbug').
color('Gris','Shelgon').
color('Gris','Spoink').
color('Gris','Steelix').
color('Gris','Terrakion').
color('Gris','Wimpod').
color('Morado','Aipom').
color('Morado','Ambipom').
color('Morado','Arbok').
color('Morado','Butterfree').
color('Morado','Chandelure').
color('Morado','Cherrim').
color('Morado','Cloyster').
color('Morado','Crabrawler').
color('Morado','Croagunk').
color('Morado','Crobat').
color('Morado','Delcatty').
color('Morado','Ditto').
color('Morado','Drapion').
color('Morado','Drifblim').
color('Morado','Drifloon').
color('Morado','Dustox').
color('Morado','Ekans').
color('Morado','Espeon').
color('Morado','Exploud').
color('Morado','Gastly').
color('Morado','Genesect').
color('Morado','Gengar').
color('Morado','Gliscor').
color('Morado','Goodra').
color('Morado','Goomy').
color('Morado','Gothita').
color('Morado','Gothitelle').
color('Morado','Gothorita').
color('Morado','Granbull').
color('Morado','Grimer').
color('Morado','Grumpig').
color('Morado','Haunter').
color('Morado','Illumise').
color('Morado','Jynx').
color('Morado','Koffing').
color('Morado','Kyogre-Primigenio').
color('Morado','Lileep').
color('Morado','Loudred').
color('Morado','Lunala').
color('Morado','Malamar').
color('Morado','Marowak-de-Alola').
color('Morado','Mega-Aerodactyl').
color('Morado','Mega-Gengar').
color('Morado','Mega-Sableye').
color('Morado','Meowth-de-Alola').
color('Morado','Mismagius').
color('Morado','Missingno').
color('Morado','Muk').
color('Morado','Munna').
color('Morado','Naganadel').
color('Morado','Nidoking').
color('Morado','Nidoran♂').
color('Morado','Nidorino').
color('Morado','Noibat').
color('Morado','Noivern').
color('Morado','Persian-de-Alola').
color('Morado','Poipole').
color('Morado','Rattata').
color('Morado','Rotom-Frio').
color('Morado','Scolipede').
color('Morado','Shellder').
color('Morado','Shuppet').
color('Morado','Skitty').
color('Morado','Skrelp').
color('Morado','Skuntank').
color('Morado','Sliggoo').
color('Morado','Starmie').
color('Morado','Stunky').
color('Morado','Swalot').
color('Morado','Tapu-Fini').
color('Morado','Tyrogue').
color('Morado','Venonat').
color('Morado','Weavile').
color('Morado','Weezing').
color('Morado','Whirlipede').
color('Morado','Zoroark').
color('Morado','Zorua').
color('Morao','Purrloin').
color('Naranja','Arcanine').
color('Naranja','Archeops').
color('Naranja','Bastiodon').
color('Naranja','Binacle').
color('Naranja','Buizel').
color('Naranja','Camerupt').
color('Naranja','Charizard').
color('Naranja','Charmander').
color('Naranja','Combee').
color('Naranja','Combusken').
color('Naranja','Corphish').
color('Naranja','Crustle').
color('Naranja','Dedenne').
color('Naranja','Deoxys').
color('Naranja','Dragonite').
color('Naranja','Dwebble').
color('Naranja','Emboar').
color('Naranja','Fletchinder').
color('Naranja','Fletchling').
color('Naranja','Floatzel').
color('Naranja','Growlithe').
color('Naranja','Kingler').
color('Naranja','Krabby').
color('Naranja','Kricketot').
color('Naranja','Landorus').
color('Naranja','Landorus-Therian').
color('Naranja','Ledyba').
color('Naranja','Magikarp').
color('Naranja','Maractus').
color('Naranja','Mega-Charizard-Y').
color('Naranja','Moltres').
color('Naranja','Mothim').
color('Naranja','Paras').
color('Naranja','Parasect').
color('Naranja','Pignite').
color('Naranja','Rotom').
color('Naranja','Rotom-Calor').
color('Naranja','Scraggy').
color('Naranja','Shieldon').
color('Naranja','Solrock').
color('Naranja','Stunfisk').
color('Naranja','Talonflame').
color('Naranja','Tapu-Koko').
color('Naranja','Teddiursa').
color('Naranja','Tepig').
color('Naranja','Torchic').
color('Naranja','Torkoal').
color('Naranja','Torracat').
color('Naranja','Trapinch').
color('Naranja','Vespiquen').
color('Naranja','Volcarona').
color('Naranja','Yanma').
color('Negro','Araquanid').
color('Negro','Beautifly').%%%%%%%%%%%
color('Negro','Bewear').
color('Negro','Blitzle').
color('Negro','Claydol').
color('Negro','Cofagrigus').
color('Negro','Cosmog').
color('Negro','Darkrai').
color('Negro','Guzzlord').
color('Negro','Houndoom').
color('Negro','Houndour').
color('Negro','Lampent').
color('Negro','Litten').
color('Negro','Marshadow').
color('Negro','Mega-Banette').
color('Negro','Mega-Charizard-X').
color('Negro','Mega-Houndoom').
color('Negro','Mightyena').
color('Negro','Misdreavus').
color('Negro','Murkrow').%%%%%%%%%%%%%%%%
color('Negro','Necrozma').
color('Negro','Ninjask').
color('Negro','Pikipek').
color('Negro','Pyukumuku').
color('Negro','Rampardos').
color('Negro','Salandit').
color('Negro','Salazzle').
color('Negro','Scrafty').
color('Negro','Seviper').
color('Negro','Sigilyph').
color('Negro','Stakataka').
color('Negro','Staraptor').
color('Negro','Staravia').
color('Negro','Starly').
color('Negro','Toucannon').
color('Negro','Tranquill').
color('Negro','Trumbeak').
color('Negro','Type:Null').
color('Negro','Umbreon').
color('Negro','Unfezant').
color('Negro','Unown').
color('Negro','Xerneas').
color('Negro','Xurkitree').
color('Negro','Yamask').
color('Negro','Zekrom').
color('Negro','Zygarde').
color('Rojo','Archen').
color('Rojo','Ariados').
color('Rojo','Bisharp').
color('Rojo','Blaziken').
color('Rojo','Buzzwole').
color('Rojo','Charmeleon').
color('Rojo','Crawdaunt').
color('Rojo','Darumaka').
color('Rojo','Delibird').
color('Rojo','Delphox').
color('Rojo','Flareon').
color('Rojo','Groudon').
color('Rojo','Groudon-Primigenio').
color('Rojo','Heatmor').
color('Rojo','Ho-Oh').
color('Rojo','Incineroar').
color('Rojo','Kricketune').
color('Rojo','Krokorok').
color('Rojo','Krookodile').
color('Rojo','Latias').
color('Rojo','Ledian').
color('Rojo','Magby').
color('Rojo','Magcargo').
color('Rojo','Magmar').
color('Rojo','Magmortar').
color('Rojo','Mega-Blaziken').
color('Rojo','Mega-Camerupt').
color('Rojo','Mega-Latias').
color('Rojo','Mega-Scizor').
color('Rojo','Octillery').
color('Rojo','Oricorio').
color('Rojo','Pansear').
color('Rojo','Scizor').
color('Rojo','Simisage').
color('Rojo','Slugma').
color('Rojo','Tapu-Bulu').
color('Rojo','Throh').
color('Rojo','Tyrantrum').
color('Rojo','Venipede').
color('Rojo','Volbeat').
color('Rojo','Volcanion').
color('Rojo','Voltorb').
color('Rojo','Wurmple').
color('Rojo','Yveltal').
color('Rosa','Alomomola').
color('Rosa','Aromatisse').
color('Rosa','Audino').
color('Rosa','Blissey').
color('Rosa','Bounsweet').
color('Rosa','Chansey').
color('Rosa','Cherubi').
color('Rosa','Clefable').
color('Rosa','Clefairy').
color('Rosa','Cleffa').
color('Rosa','Corsola').
color('Rosa','Deerling').
color('Rosa','Flaaffy').
color('Rosa','Fomantis').
color('Rosa','Gligar').
color('Rosa','Gorebyss').
color('Rosa','Happiny').
color('Rosa','Hoppip').
color('Rosa','Igglybuff').
color('Rosa','Jigglypuff').
color('Rosa','Lickilicky').
color('Rosa','Lickitung').
color('Rosa','Lurantis').
color('Rosa','Luvdisc').
color('Rosa','Medicham').
color('Rosa','Mega-Slowbro').
color('Rosa','Mew').
color('Rosa','Miltank').
color('Rosa','Mime-Jr.').
color('Rosa','Mr.Mime').
color('Rosa','Nosepass').
color('Rosa','Politoed').
color('Rosa','Porygon').
color('Rosa','Porygon-Z').
color('Rosa','Porygon2').
color('Rosa','Shellos').
color('Rosa','Shelmet').
color('Rosa','Simipour').
color('Rosa','Slowbro').
color('Rosa','Slowking').
color('Rosa','Slowpoke').
color('Rosa','Slurpuff').
color('Rosa','Smoochum').
color('Rosa','Snubbull').
color('Rosa','Spiritomb').
color('Rosa','Spritzee').
color('Rosa','Stufful').
color('Rosa','Tapu-Lele').
color('Rosa','Vivillon').
color('Rosa','Whismur').
color('Rosa','Wigglytuff').
color('Verde','Anorith').
color('Verde','Axew').
color('Verde','Bellossom').
color('Verde','Breloom').
color('Verde','Budew').
color('Verde','Bulbasaur').
color('Verde','Burmy').
color('Verde','Cacnea').
color('Verde','Cacturne').
color('Verde','Caterpie').
color('Verde','Celebi').
color('Verde','Celesteela').
color('Verde','Charjabug').
color('Verde','Chatot').
color('Verde','Chikorita').
color('Verde','Comfey').
color('Verde','Cradily').
color('Verde','Darmanitan').
color('Verde','Dewpider').
color('Verde','Duosion').
color('Verde','Electrike').
color('Verde','Finneon').
color('Verde','Florges').
color('Verde','Flygon').
color('Verde','Fraxure').
color('Verde','Grimer-de-Alola').
color('Verde','Grotle').
color('Verde','Grovyle').
color('Verde','Gulpin').
color('Verde','Hawlucha').
color('Verde','Kecleon').
color('Verde','Larvitar').
color('Verde','Leavanny').
color('Verde','Liepard').
color('Verde','Lilligant').
color('Verde','Lombre').
color('Verde','Ludicolo').
color('Verde','Mega-Rayquaza').
color('Verde','Mega-Sceptile').
color('Verde','Mega-Tyranitar').
color('Verde','Mega-Venusaur').
color('Verde','Meganium').
color('Verde','Metapod').
color('Verde','Muk-de-Alola').
color('Verde','Natu').
color('Verde','Pansage').
color('Verde','Petilil').
color('Verde','Pineco').%%%%%%%%%%%%
color('Verde','Qwilfish').
color('Verde','Rayquaza').
color('Verde','Reuniclus').
color('Verde','Roselia').
color('Verde','Roserade').
color('Verde','Rotom-Corte').
color('Verde','Sceptile').
color('Verde','Scyther').
color('Verde','Serperior').
color('Verde','Servine').
color('Verde','Sewaddle').
color('Verde','Shaymin').
color('Verde','Skiploom').
color('Verde','Snivy').
color('Verde','Solosis').
color('Verde','Spinarak').
color('Verde','Swadloon').
color('Verde','Tornadus').
color('Verde','Tornadus-Therian').
color('Verde','Torterra').
color('Verde','Treecko').
color('Verde','Tropius').
color('Verde','Trubbish').
color('Verde','Turtwig').
color('Verde','Tyranitar').
color('Verde','Vibrava').
color('Verde','Virizion').
color('Verde','Wormadam').
color('Verde','Xatu').
color('Verde','Yanmega').

'''
datos={}

cadena_sin_pokemon=cadenota.replace("pokemon","")
cadena_sin_parentesis_de_apertura=cadena_sin_pokemon.replace("(","")
cadena_sin_parentesis_de_cierre=cadena_sin_parentesis_de_apertura.replace(")","")
cadena_sin_comilla=cadena_sin_parentesis_de_cierre.replace("'","")
cadenafinal=cadena_sin_comilla.replace('.','')


cadena_sin_pokemon2=colores_de_pokes.replace("pokemon","")
cadena_sin_parentesis_de_apertura2=cadena_sin_pokemon2.replace("(","")
cadena_sin_parentesis_de_cierre2=cadena_sin_parentesis_de_apertura2.replace(")","")
cadena_sin_comilla2=cadena_sin_parentesis_de_cierre2.replace("'","")
cadena_sin_color=cadena_sin_comilla2.replace("color","")
separando_lista=cadena_sin_color.replace("\n",",")
cadena_sin_comas = separando_lista.replace(","," ")

cadenafinal2=cadena_sin_comas.replace('.','')
print(cadenafinal2)

print(cadenafinal2.split())

lista_de_pokes=cadenafinal.split()


for pokemon in range(len(lista_de_pokes)):
    if pokemon not in datos:
        datos[lista_de_pokes[pokemon]]=1
    else:
        datos[lista_de_pokes[pokemon]]+=1




